//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoHunger.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food
    {
        public int FoodId { get; set; }
        public string FoodName { get; set; }
        public Nullable<System.DateTime> Expire { get; set; }
        public string FoodType { get; set; }
        public Nullable<int> PersonQuantity { get; set; }
        public string PickupPoint { get; set; }
        public int FoodDonor { get; set; }
        public Nullable<int> TaskId { get; set; }
    
        public virtual Task Task { get; set; }
        public virtual User User { get; set; }
    }
}
